# Generated by Django 4.2 on 2025-09-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0001_initial'),
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsbuilder.dynamicform'),
        ),
    ]
